export const VEHICLE_TYPES = {
  'Ambulance55555': { prefix: 'AMB', models: ['Force Traveller', 'Tata Winger'], make: 'Various' },
  'Backhoe Loader': { prefix: 'BHL', models: ['JCB 3DX', 'CAT 424'], make: 'JCB/CAT' },
  'Bolero': { prefix: 'BOL', models: ['Bolero', 'Bolero Neo'], make: 'Mahindra' },
  'Bolero Camper': { prefix: 'BCM', models: ['Bolero Camper'], make: 'Mahindra' },
  'Boom Placer': { prefix: 'BMP', models: ['Schwing Stetter', 'Putzmeister'], make: 'Various' },
  'Bus': { prefix: 'BUS', models: ['Volvo 9400', 'Tata Marcopolo'], make: 'Various' },
  'Car': { prefix: 'CAR', models: ['Swift', 'Creta'], make: 'Various' },
  'Concrete Mixture': { prefix: 'CMX', models: ['Schwing Stetter', 'Ajax Fiori'], make: 'Various' },
  'Crane': { prefix: 'CRN', models: ['Liebherr LTM 1050', 'Grove GMK4100L'], make: 'Various' },
  'Excavator': { prefix: 'EXC', models: ['Komatsu PC210', 'Tata Hitachi EX200'], make: 'Various' },
  'Fire Truck': { prefix: 'FTR', models: ['Rosenbauer Panther', 'Brijbasi'], make: 'Various' },
  'Generator': { prefix: 'GEN', models: ['Kirloskar', 'Cummins'], make: 'Various' },
  'Hydra': { prefix: 'HYD', models: ['Escorts Hydra 14'], make: 'Escorts' },
  'Innova': { prefix: 'INV', models: ['Innova Crysta', 'Innova Hycross'], make: 'Toyota' },
  'JCB': { prefix: 'JCB', models: ['JCB 3DX', 'JCB 4DX'], make: 'JCB' },
  'Jeep': { prefix: 'JEP', models: ['Compass', 'Wrangler'], make: 'Jeep' },
  'Pick Up': { prefix: 'PCK', models: ['Isuzu D-Max', 'Tata Yodha'], make: 'Various' },
  'Road Grader': { prefix: 'RDG', models: ['CAT 120', 'Komatsu GD535'], make: 'Various' },
  'Road Roller': { prefix: 'RRL', models: ['Escorts EC5250', 'Hamm HD 99'], make: 'Various' },
  'Scorpio': { prefix: 'SCP', models: ['Scorpio-N', 'Scorpio Classic'], make: 'Mahindra' },
  'Soil Compactor': { prefix: 'SCM', models: ['Volvo SD110', 'Case 1107 EX'], make: 'Various' },
  'Sweeping Machine': { prefix: 'SWM', models: ['Dulevo 5000', 'Roots Sweep'], make: 'Various' },
  'Tanker': { prefix: 'TNK', models: ['Tata Signa', 'Ashok Leyland'], make: 'Various' },
  'Tipper': { prefix: 'TPR', models: ['Tata Prima', 'BharatBenz'], make: 'Various' },
  'Tractor': { prefix: 'TRC', models: ['John Deere 5310', 'Mahindra Arjun'], make: 'Various' },
  'Trailer': { prefix: 'TRL', models: ['Tata Signa', 'Volvo FM'], make: 'Various' },
  'Transit Mixer': { prefix: 'TMX', models: ['Tata Prima', 'Ashok Leyland'], make: 'Various' },
  'Truck': { prefix: 'TRK', models: ['Tata Ultra', 'Eicher Pro'], make: 'Various' },
  'Van': { prefix: 'VAN', models: ['Maruti Eeco', 'Tata Winger'], make: 'Various' },
  'Water Tanker': { prefix: 'WTK', models: ['Tata LPT', 'Ashok Leyland Ecomet'], make: 'Various' },
};